// Problem : Find the Difference 
/* You are given two strings s and t.
String t is generated by random shuffling string s and then add one more letter at a random position.
Return the letter that was added to t. */

#include<iostream>
using namespace std;

char findTheDifference(string s,string t){
    char ans=0;
    for(char c : s) ans^=c;
    for(char c: t) ans^=c;
    return ans;

}

int main(){
    string s = "abcd",t="abcde";
    cout << findTheDifference(s,t);
    return 0;
}